name: Latest blog post workflow
on:
    schedule:
        # Run cron job on Sunday at 2359 every week.
        - cron: '59 23 * * 0'
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                max_post_count: "5"
                feed_list: "https://codybrunner.com/feed.xml"
